config/routes.rb
Rails.application.routes.draw do
  resources :movies
  root :to => redirect('/movies')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
    col = params[:sort] || 'title ASC' # Default sort column
    @movies = Movie.order(col)
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy!

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :rating, :description, :release_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rottenpotatoes" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :release_date, style: "display: block" %>
    <%= form.text_field :release_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
  <td  class = <%= if params[:sort].nil?
    'ASC'
  
  elsif params[:sort].split(' ')[0] == 'title'
    params[:sort].split(' ')[1]
  end  %>>
    <%= movie.title %>
  </td>

  <td class = <%= unless params[:sort].nil?
    if params[:sort].split(' ')[0] == 'rating'
      params[:sort].split(' ')[1]
    end 
  end  %>> 
    
    <%= movie.rating %>
  </td>


  <td class = <%= unless params[:sort].nil?
    if params[:sort].split(' ')[0] == 'release_date'
      params[:sort].split(' ')[1]
    end 
  end  %>>
    
    <%= movie.release_date.strftime('%Y-%m-%d') %>
  </td>

app/views/movies/edit.html.erb
<% content_for :title, "Editing movie" %>

<h1 class="ind">Editing movie</h1>


<div class ="edit">
  <%= render "form", movie: @movie %>
</div>
<br>

<div class ="movie">
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Movies" %>

<h1 class="index">Movies</h1>

<div class="movies">
  <table>
    <tr>
        
        <th class = <%= if params[:sort].nil?
                          'ASC'
                        
                        elsif params[:sort].split(' ')[0] == 'title'
                          params[:sort].split(' ')[1]
                        end  %>> Title <%= link_to 'ASC',  :sort => 'title ASC' %> <%= link_to 'DESC',  :sort => 'title DESC' %></th>
        <th class = <%= unless params[:sort].nil?
                          if params[:sort].split(' ')[0] == 'rating'
                            params[:sort].split(' ')[1]
                          end 
                        end  %>>Rating <%= link_to 'ASC',  :sort => 'rating ASC' %> <%= link_to 'DESC',  :sort => 'rating DESC' %></th>
        <th class = <%= unless params[:sort].nil?
                          if params[:sort].split(' ')[0] == 'release_date'
                            params[:sort].split(' ')[1]
                          end 
                        end  %>>Release Date <%= link_to 'ASC',  :sort => 'release_date ASC' %> <%= link_to 'DESC',  :sort => 'release_date DESC' %></th>  
        
        <th>Show Movie</th>
    </tr>
    <% @movies.each do |movie| %>
      <tr>
        <%= render movie %>
        <td>
          <%= link_to "Show this movie", movie %>
        </td>
      </tr>
    <% end %>
    </table>
</div>

<%= link_to "New movie", new_movie_path %>

app/views/movies/new.html.erb
<% content_for :title, "New movie" %>

<h1>New movie</h1>
<div class = "edit">
  <%= render "form", movie: @movie %>
</div>
<br>

<div class ="movie">
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>
<div class = "movie">
  <%= render @movie %>
</div>


<div class = "show">
  <%= link_to "Edit this movie", edit_movie_path(@movie) %> |
  <%= link_to "Back to movies", movies_path %>

  <%= button_to "Destroy this movie", @movie, method: :delete %>
</div>